config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get 'signup' => 'players#signup'
  get 'new' => 'players#new'
  
  get 'players' => 'players#index'
  get 'destroy' => 'players#destroy'
  get 'statistics' => 'players#statistics'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :players

  get 'matches' => 'matches#index'
  get 'matches/new' => 'matches#new'
  resources :matches
end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :player1, class_name: "Player", foreign_key: "player1_id"
  belongs_to :player2, class_name: "Player", foreign_key: "player2_id"

  before_create :set_winner

  validates_numericality_of :player1_goals, :only_integer => true
  validates_numericality_of :player2_goals, :only_integer => true
  validates :player1_goals, inclusion: {in: 0..10}
  validates :player2_goals, inclusion: {in: 0..10}

  protected
  def set_winner
    if self.player1_goals == 10
      self.winner = player1_id
    else
      self.winner = player2_id
    end
  end

  def player1?(player_id)
    self.player1_id == player_id
  end

  def self.get_matches_by_person(player_id)
    where("player1_id = :person_id OR player2_id = :person_id", person_id: player_id)
  end

  def self.get_won_matches(player_id)
    get_matches_by_person(player_id).where("winner = ?", player_id)
  end

  def self.get_lost_matches(player_id)
    get_matches_by_person(player_id).where("winner != ?", player_id)
  end

  def self.goals_number(player_id)
    where("player1_id = ?", player_id).collect{ |i| i.player1_goals }.sum + where("player2_id = ?", player_id).collect { |i| i.player2_goals }.sum
  end

  def self.match_result
    "#{player1_goals} : #{player2_goals}"
  end

  def self.get_opponents
    "#{player1_goals} : #{player2_goals}"
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  before_action :require_admin, only: [:edit]

  def index
    @matches = Match.all.reverse
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      @player1_wins = players_won_matches(@match.player1_id)
      @player2_wins = players_won_matches(@match.player2_id)

      @player1_losts = players_losts_matches(@match.player1_id)
      @player2_losts = players_losts_matches(@match.player2_id)

      @player1_points = players_points(@player1_wins, @player1_losts)
      @player2_points = players_points(@player2_wins, @player2_losts)

      @player1_goals = players_goals(@match.player1_id)
      @player2_goals = players_goals(@match.player2_id)

      update_player(@match.player1_id, @player1_wins, @player1_losts, @player1_points, @player1_goals)
      update_player(@match.player2_id, @player2_wins, @player2_losts, @player2_points, @player2_goals)

      @player1_medal = players_medal(@match.player1_id)
      @player2_medal = players_medal(@match.player2_id)

      update_player_medal(@match.player1_id, @player1_medal)
      update_player_medal(@match.player2_id, @player2_medal)
      redirect_to matches_path
    else
      render :new
    end
  end

  def destroy
    @match = Match.find(params[:id])
    Match.find(params[:id]).destroy
    @player1_wins = players_won_matches(@match.player1_id)
    @player2_wins = players_won_matches(@match.player2_id)

    @player1_losts = players_losts_matches(@match.player1_id)
    @player2_losts = players_losts_matches(@match.player2_id)

    @player1_points = players_points(@player1_wins, @player1_losts)
    @player2_points = players_points(@player2_wins, @player2_losts)

    @player1_goals = players_goals(@match.player1_id)
    @player2_goals = players_goals(@match.player2_id)

    update_player(@match.player1_id, @player1_wins, @player1_losts, @player1_points, @player1_goals)
    update_player(@match.player2_id, @player2_wins, @player2_losts, @player2_points, @player2_goals)

    @player1_medal = players_medal(@match.player1_id)
    @player2_medal = players_medal(@match.player2_id)

    update_player_medal(@match.player1_id, @player1_medal)
    update_player_medal(@match.player2_id, @player2_medal)

    redirect_to matches_path
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    if @match.update_attributes(match_params)
      @player1_wins = players_won_matches(@match.player1_id)
      @player2_wins = players_won_matches(@match.player2_id)

      @player1_losts = players_losts_matches(@match.player1_id)
      @player2_losts = players_losts_matches(@match.player2_id)

      @player1_points = players_points(@player1_wins, @player1_losts)
      @player2_points = players_points(@player2_wins, @player2_losts)

      @player1_goals = players_goals(@match.player1_id)
      @player2_goals = players_goals(@match.player2_id)

      update_player(@match.player1_id, @player1_wins, @player1_losts, @player1_points, @player1_goals)
      update_player(@match.player2_id, @player2_wins, @player2_losts, @player2_points, @player2_goals)

      @player1_medal = players_medal(@match.player1_id)
      @player2_medal = players_medal(@match.player2_id)

      update_player_medal(@match.player1_id, @player1_medal)
      update_player_medal(@match.player2_id, @player2_medal)

      redirect_to matches_path
    else
      render 'edit'
    end
  end

  def match_params
    params.require(:match).permit(:title, :date, :startTime, :player1_id, :player2_id,
                                  :player1_goals, :player2_goals)
  end
end

def players_won_matches(player_id)
  Match.get_won_matches(player_id).count
end

def players_losts_matches(player_id)
  Match.get_lost_matches(player_id).count
end

def players_points(wins, losts)
  wins * 3 - losts
end

def players_goals(player_id)
  if Match.get_matches_by_person(player_id).count != 0
    Match.goals_number(player_id)/Match.get_matches_by_person(player_id).count
  else
    return 0
  end
end

def update_player(player_id, player_wins, player_losts, player_points, player_goals)
  Player.where(:id => player_id).update_all(wins: player_wins, losts: player_losts, points: player_points, goals: player_goals)
end

def update_player_medal(player_id, player_medal)
  Player.where(:id => player_id).update_all(badge_id: player_medal)
end

def players_medal(player_id)
  @player = Player.find(player_id)
  @badges = Badge.all
  if @player.points > @badges[1].points_limit
    @player.badge_id = @badges[1].id
  elsif @player.points > @badges[2].points_limit
    @player.badge_id = @badges[2].id
  else
    @player.badge_id = @badges[0].id
  end
  @player.badge_id
  return @player.badge_id
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>

    <form role="form">
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :date %><br>
            <%= f.date_select :date, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :startTime, "Start time" %><br>
            <%= f.time_select :startTime, class: 'form-control', class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :player1_id %><br>
            <%= collection_select(:match, :player1_id, Player.all, :id, :get_full_name) %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :player2_id %><br>
            <%= collection_select(:match, :player2_id, Player.all, :id, :get_full_name) %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :player1_goals %><br>
            <%= f.number_field(:player1_goals, in: 0..10) %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :player2_goals %><br>
            <%= f.number_field(:player2_goals, in: 0..10) %>
          </div>
        </div>
      </div>

      <%= f.submit button_label, class: "btn-submit" %>
      <%= link_to 'Back', matches_path, class: "btn-submit" %>
    </form>
<% end %>

<script>
    var y, ytext;
    var y2, y2text;

    $(document).ready(function () {
        y = $('#match_player1_id').find(":selected").val();
        ytext = $('#match_player1_id').find(":selected").text();


        $("#match_player2_id option[value=" + y + "]").remove();

        y2 = $('#match_player2_id').find(":selected").val();
        y2text = $('#match_player2_id').find(":selected").text();
        $("#match_player1_id option[value=" + y2 + "]").remove();

    });


    $("#match_player1_id").on("change", function (e) {
        var x = $('#match_player1_id').find(":selected").val();
        var xtext = $('#match_player1_id').find(":selected").text();

        $("#match_player2_id option[value=" + x + "]").remove();

        $('#match_player2_id').append($('<option>', {
            value: y,
            text: ytext
        }));

        y = x;
        ytext = xtext;
    });

    $("#match_player2_id").on("change", function (e) {
        var x = $('#match_player2_id').find(":selected").val();
        var xtext = $('#match_player2_id').find(":selected").text();

        $("#match_player1_id option[value=" + x + "]").remove();

        $('#match_player1_id').append($('<option>', {
            value: y2,
            text: y2text
        }));

        y2 = x;
        y2text = xtext;
    });

    $("#match_player1_goals").on("change", function (e) {
        if ($("#match_player1_goals").val() < 10) {
            $("#match_player2_goals").val(10);
            $("#match_player2_goals").attr('max', 10);
        }
        else if ($("#match_player1_goals").val() == 10) {
            $("#match_player2_goals").attr('max', 9);
        }
    });

    $("#match_player2_goals").on("change", function (e) {
        if ($("#match_player2_goals").val() < 10) {
            $("#match_player1_goals").val(10);
            $("#match_player1_goals").attr('max', 10);
        }
        else if ($("#match_player2_goals").val() == 10) {
            $("#match_player1_goals").attr('max', 9);
        }
    });


</script>

app/views/matches/edit.html.erb
<div class="login">
  <div class="container">
    <h1>Edit the match</h1>
    <%= render :partial => "form", :locals => { :button_label => "Save changes" } %>
  </div>
</div>
</div>

app/views/matches/index.html.erb
<div class="index">
  <div class="container">

    <h1>Last matches</h1>

    <div class="box">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>Title</th>
            <th></th>
            <th>Player1</th>
            <th>Result</th>
            <th>Player2</th>
            <th></th>
            <th>Date</th>
            <th>Start time</th>
            <% if current_player && current_player.admin? %>
                <th></th>
                <th></th>
            <% end %>
          </tr>
          </thead>

          <tbody>
          <% @matches.each do |match| %>
              <tr>
                <td><%= match.title %></td>

                <% if Player.exists?(match.player1_id) %>
                    <td><%= gravatar_for Player.find(match.player1_id), size: "80" %></td>
                    <td><%= Player.find(match.player1_id).get_full_name %></td>
                <% else %>
                    <td><%= image_tag 'deleted_user.png', size: "80" %></td>
                    <td>Player deleted</td>
                <% end %>
                <td><%= match.player1_goals %> : <%= match.player2_goals %></td>
                <% if Player.exists?(match.player2_id) %>
                    <td><%= Player.find(match.player2_id).get_full_name %></td>
                    <td><%= gravatar_for Player.find(match.player2_id), size: "80" %></td>
                <% else %>
                    <td>Gracz usunięty</td>
                <% end %>

                <td><%= match.date %></td>
                <td><%= match.startTime.strftime("%H : %M") %></td>
                <% if current_player && current_player.admin? %>
                    <td class="icon"><%= link_to "", match, method: :delete,
                                                 data: {confirm: "Are you sure?"}, class: "delete" %></td>
                    <td class="icon"><%= link_to "", edit_match_path(match), class: "edit" %></td>
                <% end %>
          <% end %>
          </tr>
          </tbody>
        </table>
      </div>

      <% if current_player && current_player.admin? %>
          <%= link_to 'New Match', new_match_path, class: "btn-submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/matches/new.html.erb
<div class="login">
  <div class="container">
    <h1>Add new match</h1>
    <%= render :partial => "form", :locals => { :button_label => "Create match" } %>
  </div>
</div>