config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get 'signup' => 'players#signup'
  get 'new' => 'players#new'
  
  get 'players' => 'players#index'
  get 'destroy' => 'players#destroy'
  get 'statistics' => 'players#statistics'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :players

  get 'matches' => 'matches#index'
  get 'matches/new' => 'matches#new'
  resources :matches
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <ul>
      <li><a href="#">About</a></li>
      <li><a href="#">Terms</a></li>
    </ul>
    <p>© 2015 Paula Grzesiak</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="container">
  </div>
</div>

<div class="menu">
  <div class="container">
    <ul class="nav">
      <% if current_player %>
          <li class="dropdown">
            <a class="dropdown-toggle active" data-toggle="dropdown" href="#">Account <span class="caret"></span></a>
            <ul class="nav dropdown-menu">
              <li class="ddown"><%= link_to "Profile", current_player %></li>
              <li class="ddown"><%= link_to "Settings", edit_player_path(current_player) %></li>
              <li class="ddown"><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
          <li><%= link_to "Players", players_path %></li>
          <li><%= link_to "Matches", matches_path %></li>
      <% else %>
          <li class="active"><%= link_to "Log in", login_path %></a></li>
      <% end %>
      <li><%= link_to "Statistics", statistics_path %></li>
      <li><%= link_to "Welcome", root_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>F2tracker</title>
  <link href='https://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--<%= stylesheet_link_tag 'application', 'thickbox' %>-->
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>